title: Swift SshConfig Lib Page
tagline: Swift SshConfig API documentation
description: >-
  An SSH config parser library for Swift with a fancy API

url: https://xxlabaza.github.io/SshConfig
email: xxlabaza@gmail.com

author:
  name: Artem Labazin
  twitter: xxlabaza
twitter:
  username: xxlabaza
github:
  username: xxlabaza

theme: jekyll-theme-modernist
toc: true
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
