//===----------------------------------------------------------------------===//
//
// This source file is part of the SshConfig open source project
//
// Copyright (c) 2021 Artem Labazin
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SshConfig project contributors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if !canImport(ObjectiveC)
import XCTest

extension ConfigDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigDecoderTests = [
        ("testComplexConfig", testComplexConfig),
        ("testMultipleOccursOfSingleValue", testMultipleOccursOfSingleValue),
        ("testPasingOf_addKeysToAgent", testPasingOf_addKeysToAgent),
        ("testPasingOf_addressFamily", testPasingOf_addressFamily),
        ("testPasingOf_batchMode", testPasingOf_batchMode),
        ("testPasingOf_bindAddress", testPasingOf_bindAddress),
        ("testPasingOf_bindInterface", testPasingOf_bindInterface),
        ("testPasingOf_canonicalDomains", testPasingOf_canonicalDomains),
        ("testPasingOf_canonicalizeFallbackLocal", testPasingOf_canonicalizeFallbackLocal),
        ("testPasingOf_canonicalizeHostname", testPasingOf_canonicalizeHostname),
        ("testPasingOf_canonicalizeMaxDots", testPasingOf_canonicalizeMaxDots),
        ("testPasingOf_canonicalizePermittedCNAMEs", testPasingOf_canonicalizePermittedCNAMEs),
        ("testPasingOf_caSignatureAlgorithms", testPasingOf_caSignatureAlgorithms),
        ("testPasingOf_certificateFile", testPasingOf_certificateFile),
        ("testPasingOf_challengeResponseAuthentication", testPasingOf_challengeResponseAuthentication),
        ("testPasingOf_checkHostIP", testPasingOf_checkHostIP),
        ("testPasingOf_ciphers", testPasingOf_ciphers),
        ("testPasingOf_clearAllForwardings", testPasingOf_clearAllForwardings),
        ("testPasingOf_compression", testPasingOf_compression),
        ("testPasingOf_connectionAttempts", testPasingOf_connectionAttempts),
        ("testPasingOf_connectTimeout", testPasingOf_connectTimeout),
        ("testPasingOf_controlMaster", testPasingOf_controlMaster),
        ("testPasingOf_controlPath", testPasingOf_controlPath),
        ("testPasingOf_controlPersist", testPasingOf_controlPersist),
        ("testPasingOf_dynamicForward", testPasingOf_dynamicForward),
        ("testPasingOf_enableSSHKeysign", testPasingOf_enableSSHKeysign),
        ("testPasingOf_escapeChar", testPasingOf_escapeChar),
        ("testPasingOf_exitOnForwardFailure", testPasingOf_exitOnForwardFailure),
        ("testPasingOf_fingerprintHash", testPasingOf_fingerprintHash),
        ("testPasingOf_forwardAgent", testPasingOf_forwardAgent),
        ("testPasingOf_forwardX11", testPasingOf_forwardX11),
        ("testPasingOf_forwardX11Timeout", testPasingOf_forwardX11Timeout),
        ("testPasingOf_forwardX11Trusted", testPasingOf_forwardX11Trusted),
        ("testPasingOf_gatewayPorts", testPasingOf_gatewayPorts),
        ("testPasingOf_globalKnownHostsFile", testPasingOf_globalKnownHostsFile),
        ("testPasingOf_gssApiAuthentication", testPasingOf_gssApiAuthentication),
        ("testPasingOf_gssApiDelegateCredentials", testPasingOf_gssApiDelegateCredentials),
        ("testPasingOf_hashKnownHosts", testPasingOf_hashKnownHosts),
        ("testPasingOf_hostbasedAcceptedAlgorithms", testPasingOf_hostbasedAcceptedAlgorithms),
        ("testPasingOf_hostbasedAuthentication", testPasingOf_hostbasedAuthentication),
        ("testPasingOf_hostKeyAlgorithms", testPasingOf_hostKeyAlgorithms),
        ("testPasingOf_hostKeyAlias", testPasingOf_hostKeyAlias),
        ("testPasingOf_hostname", testPasingOf_hostname),
        ("testPasingOf_identitiesOnly", testPasingOf_identitiesOnly),
        ("testPasingOf_identityAgent", testPasingOf_identityAgent),
        ("testPasingOf_identityFile", testPasingOf_identityFile),
        ("testPasingOf_ignoreUnknown", testPasingOf_ignoreUnknown),
        ("testPasingOf_include", testPasingOf_include),
        ("testPasingOf_ipqos", testPasingOf_ipqos),
        ("testPasingOf_kbdInteractiveAuthentication", testPasingOf_kbdInteractiveAuthentication),
        ("testPasingOf_kbdInteractiveDevices", testPasingOf_kbdInteractiveDevices),
        ("testPasingOf_kexAlgorithms", testPasingOf_kexAlgorithms),
        ("testPasingOf_knownHostsCommand", testPasingOf_knownHostsCommand),
        ("testPasingOf_localCommand", testPasingOf_localCommand),
        ("testPasingOf_localForward", testPasingOf_localForward),
        ("testPasingOf_logLevel", testPasingOf_logLevel),
        ("testPasingOf_logVerbose", testPasingOf_logVerbose),
        ("testPasingOf_macs", testPasingOf_macs),
        ("testPasingOf_noHostAuthenticationForLocalhost", testPasingOf_noHostAuthenticationForLocalhost),
        ("testPasingOf_numberOfPasswordPrompts", testPasingOf_numberOfPasswordPrompts),
        ("testPasingOf_passwordAuthentication", testPasingOf_passwordAuthentication),
        ("testPasingOf_permitLocalCommand", testPasingOf_permitLocalCommand),
        ("testPasingOf_permitRemoteOpen", testPasingOf_permitRemoteOpen),
        ("testPasingOf_pkcs11Provider", testPasingOf_pkcs11Provider),
        ("testPasingOf_port", testPasingOf_port),
        ("testPasingOf_preferredAuthentications", testPasingOf_preferredAuthentications),
        ("testPasingOf_proxyCommand", testPasingOf_proxyCommand),
        ("testPasingOf_proxyJump", testPasingOf_proxyJump),
        ("testPasingOf_proxyUseFdpass", testPasingOf_proxyUseFdpass),
        ("testPasingOf_pubkeyAcceptedAlgorithms", testPasingOf_pubkeyAcceptedAlgorithms),
        ("testPasingOf_pubkeyAuthentication", testPasingOf_pubkeyAuthentication),
        ("testPasingOf_rekeyLimit", testPasingOf_rekeyLimit),
        ("testPasingOf_remoteCommand", testPasingOf_remoteCommand),
        ("testPasingOf_remoteForward", testPasingOf_remoteForward),
        ("testPasingOf_requestTTY", testPasingOf_requestTTY),
        ("testPasingOf_revokedHostKeys", testPasingOf_revokedHostKeys),
        ("testPasingOf_securityKeyProvider", testPasingOf_securityKeyProvider),
        ("testPasingOf_sendEnv", testPasingOf_sendEnv),
        ("testPasingOf_serverAliveCountMax", testPasingOf_serverAliveCountMax),
        ("testPasingOf_serverAliveInterval", testPasingOf_serverAliveInterval),
        ("testPasingOf_setEnv", testPasingOf_setEnv),
        ("testPasingOf_streamLocalBindMask", testPasingOf_streamLocalBindMask),
        ("testPasingOf_streamLocalBindUnlink", testPasingOf_streamLocalBindUnlink),
        ("testPasingOf_strictHostKeyChecking", testPasingOf_strictHostKeyChecking),
        ("testPasingOf_syslogFacility", testPasingOf_syslogFacility),
        ("testPasingOf_tcpKeepAlive", testPasingOf_tcpKeepAlive),
        ("testPasingOf_tunnel", testPasingOf_tunnel),
        ("testPasingOf_tunnelDevice", testPasingOf_tunnelDevice),
        ("testPasingOf_unknown", testPasingOf_unknown),
        ("testPasingOf_updateHostKeys", testPasingOf_updateHostKeys),
        ("testPasingOf_user", testPasingOf_user),
        ("testPasingOf_userKnownHostsFile", testPasingOf_userKnownHostsFile),
        ("testPasingOf_verifyHostKeyDNS", testPasingOf_verifyHostKeyDNS),
        ("testPasingOf_visualHostKey", testPasingOf_visualHostKey),
        ("testPasingOf_xAuthLocation", testPasingOf_xAuthLocation),
        ("testSimpleConfig", testSimpleConfig),
        ("testUnableToDecode", testUnableToDecode),
    ]
}

extension ConfigEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigEncoderTests = [
        ("testEncodeSendEnv", testEncodeSendEnv),
        ("testEncodeSetEnv", testEncodeSetEnv),
        ("testEncodeUparsed", testEncodeUparsed),
        ("testSimple", testSimple),
    ]
}

extension ConfigParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigParserTests = [
        ("testEmptyKeyToken", testEmptyKeyToken),
        ("testEmptyValueToken", testEmptyValueToken),
        ("testExample", testExample),
        ("testIllegalTokensDelimiter", testIllegalTokensDelimiter),
        ("testNoAliasesForHost", testNoAliasesForHost),
        ("testNoPropertiesForHost", testNoPropertiesForHost),
        ("testUnexpectedToken", testUnexpectedToken),
    ]
}

extension ConfigResolveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigResolveTests = [
        ("testInternalAliasesPattern_All", testInternalAliasesPattern_All),
        ("testInternalAliasesPattern_SpecificAlias", testInternalAliasesPattern_SpecificAlias),
        ("testInternalAliasesPattern_SpecificAliases", testInternalAliasesPattern_SpecificAliases),
        ("testInternalAliasesPattern_SpecificHost", testInternalAliasesPattern_SpecificHost),
        ("testInternalAliasesPattern_SpecificHosts", testInternalAliasesPattern_SpecificHosts),
        ("testResolveOrder", testResolveOrder),
        ("testSimpleConfig", testSimpleConfig),
        ("testWildcardConfig", testWildcardConfig),
    ]
}

extension ConfigTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigTests = [
        ("testHostsAccess", testHostsAccess),
    ]
}

extension HostTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HostTests = [
        ("testEquals", testEquals),
        ("testMatch", testMatch),
        ("testPropertiesAccess", testPropertiesAccess),
    ]
}

extension PatternTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PatternTests = [
        ("testNamedGroupsWithoutPort", testNamedGroupsWithoutPort),
        ("testNamedGroupsWithPort", testNamedGroupsWithPort),
        ("testWildcardExact", testWildcardExact),
        ("testWildcardExactlyOneCharacter", testWildcardExactlyOneCharacter),
        ("testWildcardZeroOrMoreCharacters", testWildcardZeroOrMoreCharacters),
    ]
}

extension TokenizerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenizerTests = [
        ("testBasicTokensChecks", testBasicTokensChecks),
        ("testEmptyContent", testEmptyContent),
        ("testEmptyKeyToken", testEmptyKeyToken),
        ("testEmptyValueToken", testEmptyValueToken),
        ("testIllegalTokensDelimiter", testIllegalTokensDelimiter),
        ("testWholeIterator", testWholeIterator),
    ]
}

extension UsageExample {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsageExample = [
        ("testConfigDump", testConfigDump),
        ("testConfigFromJsonData", testConfigFromJsonData),
        ("testConfigFromJsonString", testConfigFromJsonString),
        ("testConfigInit", testConfigInit),
        ("testConfigLoad", testConfigLoad),
        ("testConfigParse", testConfigParse),
        ("testConfigParser", testConfigParser),
        ("testConfigResolve", testConfigResolve),
        ("testConfigToJsonData", testConfigToJsonData),
        ("testConfigToJsonString", testConfigToJsonString),
        ("testConfigToString", testConfigToString),
        ("testDecoder", testDecoder),
        ("testEmptyKeyToken", testEmptyKeyToken),
        ("testEmptyValueToken", testEmptyValueToken),
        ("testEncoder", testEncoder),
        ("testExample", testExample),
        ("testHostInit2", testHostInit2),
        ("testHostInit", testHostInit),
        ("testIllegalTokensDelimiter", testIllegalTokensDelimiter),
        ("testNoAliasForHost", testNoAliasForHost),
        ("testNoPropertiesForHost", testNoPropertiesForHost),
        ("testPropertiesDefaults", testPropertiesDefaults),
        ("testReadme1", testReadme1),
        ("testReadme2", testReadme2),
        ("testUnableToDecode", testUnableToDecode),
        ("testUnableToDump", testUnableToDump),
        ("testUnableToLoad", testUnableToLoad),
        ("testUnexpectedToken", testUnexpectedToken),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConfigDecoderTests.__allTests__ConfigDecoderTests),
        testCase(ConfigEncoderTests.__allTests__ConfigEncoderTests),
        testCase(ConfigParserTests.__allTests__ConfigParserTests),
        testCase(ConfigResolveTests.__allTests__ConfigResolveTests),
        testCase(ConfigTests.__allTests__ConfigTests),
        testCase(HostTests.__allTests__HostTests),
        testCase(PatternTests.__allTests__PatternTests),
        testCase(TokenizerTests.__allTests__TokenizerTests),
        testCase(UsageExample.__allTests__UsageExample),
    ]
}
#endif
